---
name: tokolink
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.0
  get_it: ^4.0.2
  shared_preferences: ^0.5.8
  sembast: ^2.4.7+4
  intl: ^0.16.1
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  google_fonts: ^1.1.0
  keyboard_visibility: ^0.5.6
  pin_code_text_field: ^1.6.0
  carousel_slider: ^2.2.1
  dotted_border: ^1.0.6
  flutter_svg: null
  chopper: ^3.0.6
  equatable: ^1.2.5
  shimmer: ^1.1.2
  flutter_countdown_timer:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: null
  chopper_generator: ^3.0.6
  build_runner: ^1.10.3
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/img/
